### ISSUE TITLE
virus in guiminer-20110701.exe!

### ISSUE THREAD

**Issue by univer** [Kiv/poclbm#22]
There is a virus reported by Avira in guiminer\miners\ufasoft\bitcoin-miner.exe. And the file is really bigger than the newest official ufasoft\bitcoin-miner.exe. Please check it!!!

**Comment by Kiv** [comment]
That miner is an older version than the latest official one which is why the file size differs. The version packaged with GUIMiner has been in there for months and nobody has reported any virus issues.

The virus warning is a false positive and someone has already submitted it for review. I'm not sure what I will do in the future if they don't clean it up - I might have to ask people to separately download ufasoft miner since from the poll only a few percent of users are using it.

**Comment by Kiv** [comment]
Since only a few percent of GUIMiner users run ufasoft, I'm going to unbundle it from the package which should resolve this issue.
