### ISSUE TITLE
My computer freeze when stopping the miner

### ISSUE THREAD

**Issue by jstebenne** [Kiv/poclbm#49]
Hi,

When I stop the CUDA miner, my computer completly freeze and I cant do anything.

I can mouve the mouse cursor, CTRL-ALT-DELETE doesnt work, same for ALT-F4. I think that when I stop the miner, my Nvidia card simply crash and I have to restart my computer.

**Comment by Kiv** [comment]
Hi, I haven't heard of such an issue and it's very strange. The miner works fine while it is going and this only happens when it stops? Are you able to use other miners?

Unfortunately I don't think I can fix anything for you, I don't work on the miner directly just the GUI for it. Your best bet is probably to post on the Bitcoin forums with as much detail as you can, and I bet someone will be able to troubleshoot it with you.

**Comment by techman05** [comment]
Are you just closing the program altogether when it crashes. I did that once and tried never to do again. I think if you didn't , try pressing stop button for your miners before closing the app. My luck is its not stopping everything when you do it that way.

@Kiv Can you put a "check if everything's stopped command" in the exit buttons so you kill stragglers("Stop") before the app closes?

**Comment by jstebenne** [comment]
No, its when I am clicking the stop button. I never clos the miner completly, just stop it. But I stopped using guiminer because I changed pool for BitMinter, but the bitminter miner does not have CUDA mining, so I might go back to GUIMiner. I havent tried stopping with cude enable for a long time now, so I dont know if its fixed.
