### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by ToriAmos1963** [Kiv/poclbm#8]
Could you clarify something?  When I look at my summary page, there is a column labeled Accepted, but there are two number listed for each worker.  What is the number outside the parenthesis and the number inside the parenthesis?  Same question for the Stale column.

If I have two cards running two different miners, do I need to register two different workers?  For example, I joined slush pool and created a single worker.  I'm using the single worker for both my miners.  Is this right or do I need to set up a separate worker for each miner?

Thanks,
Ali

**Comment by Kiv** [comment]
Hi, if it says 1000 (50) it means 1000 shares accepted since the miner has been running, and 50 of those in the last hour. It's useful to see the shares per hour, since if it drops a lot then something is going wrong. This is listed in the FAQ on the forum page but you're right that I should probably make the README comprehensive. I just haven't had time lately to give it the proper treatment :)

There should be no issue with re-using a worker. I think the only reason you would want separate ones is if you wanted to track their stats separately.
